version: '3.9'
services:
  ui:
    build: 'ui/'
    command: ['yarn', 'build', '--watch']
    entrypoint: []
    working_dir: /app

    volumes:
      - '$PWD/ui:/app'

  api:
    build: 'api/'
    command: ['cargo', 'run']
    working_dir: /app

    privileged: true
    network_mode: host
    volumes:
      - '$PWD:/app'
      - '$PWD/dev.toml:/etc/vagabond.toml'
      - '$PWD/data:/data'
`